CC = zcc
CCFLAGS = +msx
OUTPUT_DIR = ../dist

all: $(OUTPUT_DIR)/lsusb.com
.PHONY: all clean copy

$(OUTPUT_DIR)/lsusb.com: lsusb.c lsusb.h
	$(CC) $(CCFLAGS) -subtype=msxdos -o$(OUTPUT_DIR)/lsusb.com $< 

clean:
	-rm $(OUTPUT_DIR)/*.rom
	-rm $(OUTPUT_DIR)/*.com
	-rm $(OUTPUT_DIR)/*.bin
	-rm $(OUTPUT_DIR)/*.sym
